### PR TITLE
5 traceroute visualizer

### PR DESCRIPTION
**Pull request by nevermore23274**
- Updated to Streamlit 1.28.2
- Fixed catch warnings in certificate_lookup() and dns_lookup()
- Fixed non-zero exit-status on subprocess run in certificate_lookup()
- Added traceroute visualization, works with enter key

### CODE REVIEW

**Review by tyoung-99 — CHANGES_REQUESTED** [review]
You used the sidebar for some of your user input, which is fine with the current sidebar, but Oscar's updates (#43) would push that further down. It's probably best to keep the sidebar for navigation and have all user input on the page itself, but if you have a better idea, let me know.

There's an extra row in your raw output table. I tried printing the list of lines you're using, and it looks like you just didn't skip enough lines, since the headers are the 2nd item, not the 1st like you thought.
image

Is it necessary to allow the user to set the scatter radius? It doesn't actually increase the precision, just the size of the plotted points, so it's only visual. Personally, I think it makes sense to just set a particular size for the points and leave it. You could also set a minimum radius in pixels, if you want them visible when zoomed out, but unobtrusive when zoomed in.

**Comment by nevermore23274** [comment]
Why is there an issue with allowing the altering of something "just visual"? It's hard to gauge what users would use, just like how maybe I'd like some output to be in a table, where others just want it in the exact terminal output. If nothing else, it's simply demonstrating the use of the slider in a UI way.

Looking at his PR, I'm not sure that me having things in the side would affect it at all. I may move it down for a bit, but it doesn't look like it actually breaks anything.

The table you're correct on so I fixed that, as well will move things out of the side bar though I don't know if having a ton of button and sliders on the page, rather than just the indexed information, is the route we should be moving with this. (otherwise we'd just have zero buttons and sliders and only use searchable things)

**Comment by tyoung-99** [comment]
It's not that there's an issue with the inclusion of the slider, it's just that it's not necessary. It doesn't hurt one way or the other, so if you want to have it, it's not a problem to keep it in.

I wasn't worried about input in the sidebar breaking anything, just that it might look weird on smaller screens or be potentially difficult to use if you had to scroll for it. I didn't combine the code myself so I don't know what it would actually look like, just that Oscar's sidebar change is longer. As long as it's all still easily visible, I imagine input should be fine in the sidebar.

**Review by TheSirLancelot — APPROVED** [review]
Looks good to me! Great work

**Pull request merged**
