### PR TITLE
Update living documents

### PR DESCRIPTION
**Pull request by TheSirLancelot**
Note: we have #62 open for wget so I marked that as complete. ~We are still waiting for @Rey41888  to submit a PR for #17~

Edit: #17 was closed. Will update the branch once we decide what's going to replace the two features.

### CODE REVIEW

**Comment by TheSirLancelot** [comment]
Blocked by #80

**Comment by tyoung-99** [comment]
#80 is resolved. No longer blocked.

**Review by TheSirLancelot — COMMENTED** [review]
Everything looks good here, but I can't approve this PR since I was the original author.

**Review by oavf15 — APPROVED** [review]
Everything looks good!

**Pull request merged**
