### PR TITLE
43 make the splash page pretty

### LINKED ISSUE #43: Make the splash page pretty
The main page of the web-app is still the "Shadow Suite" that we started with. We need to come up with something that matches what our app actually is.

### PR DESCRIPTION
**Pull request by tyoung-99**
Updated splash page, page name, and favicon to be particular to our app, with a stylized logo.
Oscar modified navbar to look nicer and work better with unit tests.
Closes #43

### CODE REVIEW

**Comment by oavf15** [comment]
Currently blocked as no tests with webkit will pass on Github; they only pass locally.

**Comment by oavf15** [comment]
Moving to review, since using Playwright v1.38.0 fixes the WebKit problem. The home page test was also added and runs without error for all browsers.

**Comment by tyoung-99** [comment]
It looks like my HTTP header tool is causing a failure. I'll take a look at it.

**Comment by tyoung-99** [comment]
I temporarily commented out the failing HTTP header test so this can be merged. I'll make a new branch to fix that issue.

**Review by TheSirLancelot — APPROVED** [review]
Tests pass. Looks good

**Pull request merged**
